#include<stdio.h>
int main()
{
    long fact[]={1,1,2,6,24,120,720,5040,40320,362880},x,a,b,c,d,e,f,g,i,j,k,l,m,n,o,sum,t[10],temp,temp1,flag;

    for(i=1;i<10;i++)
    {
        a=fact[i];
        for(j=0;j<10;j++)
        {
            b=fact[j];
            sum=a+b;
            if(sum>9&&sum<100)
            {
                for(x=0;x<10;x++)
                    t[x]=0;
                t[i]=t[i]+1;
                t[j]=t[j]+1;
                flag=1;
                temp=sum;
                while(temp>0&&flag)
                {
                    temp1=temp%10;
                    temp=temp/10;
                   if(t[temp1]==0)
                        flag=0;
                   else
                      t[temp1]=t[temp1]-1;
                }
                if(flag==1)
                    printf("%ld\n",sum);
            }
            for(k=0;k<10;k++)
            {
                c=fact[k];
                sum=a+b+c;
            if(sum>99&&sum<1000)
            {
                for(x=0;x<10;x++)
                    t[x]=0;
                t[i]=t[i]+1;
                t[j]=t[j]+1;
                t[k]=t[k]+1;
                flag=1;
                temp=sum;
                while(temp>0&&flag)
                {
                    temp1=temp%10;
                    temp=temp/10;
                   if(t[temp1]==0)
                        flag=0;
                   else
                      t[temp1]=t[temp1]-1;
                }
                if(flag==1)
                    printf("%ld\n",sum);
            }
                for(l=0;l<10;l++)
                {
                    d=fact[l];
                    sum=a+b+c+d;
                    if(sum>999&&sum<10000)
                    {
                        for(x=0;x<10;x++)
                            t[x]=0;
                        t[i]=t[i]+1;
                        t[j]=t[j]+1;
                        t[k]=t[k]+1;
                        t[l]=t[l]+1;
                        flag=1;
                        temp=sum;
                        while(temp>0&&flag)
                        {
                            temp1=temp%10;
                            temp=temp/10;
                           if(t[temp1]==0)
                                flag=0;
                           else
                              t[temp1]=t[temp1]-1;
                        }
                        if(flag==1)
                            printf("%ld\n",sum);
                       }
                    for(m=0;m<10;m++)
                    {
                        e=fact[m];
                                sum=a+b+c+d+e;
                            if(sum>9999&&sum<100000)
                            {
                                for(x=0;x<10;x++)
                                    t[x]=0;
                                t[i]=t[i]+1;
                                t[j]=t[j]+1;
                                t[k]=t[k]+1;
                                t[l]=t[l]+1;
                                t[m]=t[m]+1;
                                flag=1;
                                temp=sum;
                                while(temp>0&&flag)
                                {
                                    temp1=temp%10;
                                    temp=temp/10;
                                   if(t[temp1]==0)
                                        flag=0;
                                   else
                                      t[temp1]=t[temp1]-1;
                                }
                                if(flag==1)
                                    printf("%ld\n",sum);
                            }
                        for(n=0;n<10;n++)
                        {
                            f=fact[n];
                                sum=a+b+c+d+e+f;
                            if(sum>99999&&sum<1000000)
                            {
                                for(x=0;x<10;x++)
                                    t[x]=0;
                                t[i]=t[i]+1;
                                t[j]=t[j]+1;
                                t[k]=t[k]+1;
                                t[l]=t[l]+1;
                                t[m]=t[m]+1;
                                t[n]=t[n]+1;
                                flag=1;
                                temp=sum;
                                while(temp>0&&flag)
                                {
                                    temp1=temp%10;
                                    temp=temp/10;
                                   if(t[temp1]==0)
                                        flag=0;
                                   else
                                      t[temp1]=t[temp1]-1;
                                }
                                if(flag==1)
                                    printf("%ld\n",sum);
                                }
                            for(o=0;o<10;o++)
                            {
                                g=fact[o];
                                 sum=a+b+c+d+e+f;
                            if(sum>999999&&sum<10000000)
                            {
                                for(x=0;x<10;x++)
                                    t[x]=0;
                                t[i]=t[i]+1;
                                t[j]=t[j]+1;
                                t[k]=t[k]+1;
                                t[l]=t[l]+1;
                                t[m]=t[m]+1;
                                t[n]=t[n]+1;
                                t[o]=t[o]+1;
                                flag=1;
                                temp=sum;
                                while(temp>0&&flag)
                                {
                                    temp1=temp%10;
                                    temp=temp/10;
                                   if(t[temp1]==0)
                                        flag=0;
                                   else
                                      t[temp1]=t[temp1]-1;
                                }
                                if(flag==1)
                                    printf("%ld\n",sum);
                            }

                            }
                        }
                    }
                }
            }
        }
    }
}


